theme: jekyll-theme-cayman
title: "Oneida (Canada) Dictionary of Words and Phrases"
description: "A dictionary made from the Oneida Words & Phrases page of oneidalanguage.ca"
author: "CutThroat78"
show_downloads: false
github:
   is_project_page: false
