theme: jekyll-theme-slate
author: "CutThroat78"
title: "Oneida (Canada) Words & Phrases"
description: "Tables of words & phrases for learners learning Oneida (Canada) language"
show_downloads: false
github:
   is_project_page: false